apiVersion: apps/v1
kind: Deployment
metadata:
  name: patient-deployment
  labels:
    app: patient
spec:
  replicas: 3
  selector:
    matchLabels:
      app: patient
  template:
    metadata:
      labels:
        app: patient
    spec:
      containers:
      - name: patient
        image: 825765405000.dkr.ecr.us-east-1.amazonaws.com/sattiipatwala:patient-service
        ports:
        - containerPort: 5000
        imagePullPolicy: Always
