apiVersion: apps/v1
kind: Deployment
metadata:
  name: patient-deployment
  labels:
    app: patient
spec:
  replicas: 2
  selector:
    matchLabels:
      app: patient
  template:
    metadata:
      labels:
        app: patient
    spec:
      containers:
      - name: patient
        image: 543003945919.dkr.ecr.us-east-1.amazonaws.com/pixels-repo:patient-service
        ports:
        - containerPort: 5000
