name: Build and Push Docker Images to ECR

on:
  push:
    branches: [ main ]
    paths:
      - 'microservices/**'
      - '.github/workflows/docker-build.yaml'

jobs:
  build-and-push:
    name: Build and Push Docker Images
    runs-on: ubuntu-latest

    env:
      AWS_REGION: ${{ secrets.AWS_REGION }}
      ECR_REPO_NAME: ${{ secrets.ECR_REPO_NAME }}

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push Appointment Service image
        working-directory: microservices/appointment-service
        run: |
          IMAGE_TAG=appointment-service:latest
          ECR_URI=${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPO_NAME }}-appointment
          docker build -t $IMAGE_TAG .
          docker tag $IMAGE_TAG $ECR_URI
          docker push $ECR_URI

      - name: Build, tag, and push Patient Service image
        working-directory: microservices/patient-service
        run: |
          IMAGE_TAG=patient-service:latest
          ECR_URI=${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPO_NAME }}-patient
          docker build -t $IMAGE_TAG .
          docker tag $IMAGE_TAG $ECR_URI
          docker push $ECR_URI
