name: Build and Push Docker Images to ECR

on:
  push:
    branches: [ main ]
    paths:
      - 'microservices/**'
      - '.github/workflows/docker-build.yaml'

jobs:
  build-and-push:
    name: Build and Push Docker Images
    runs-on: ubuntu-latest

    env:
      AWS_REGION: ${{ secrets.AWS_REGION }}
      ACCOUNT_ID: ${{ secrets.ACCOUNT_ID }}
      ECR_REPO_NAME: ${{ secrets.ECR_REPO_NAME }}

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push Appointment Service image
        working-directory: microservices/appointment-service
        run: |
          IMAGE_NAME=appointment-service
          IMAGE_URI=${ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${ECR_REPO_NAME}:$IMAGE_NAME
          docker build -t $IMAGE_NAME .
          docker tag $IMAGE_NAME $IMAGE_URI
          docker push $IMAGE_URI

      - name: Build, tag, and push Patient Service image
        working-directory: microservices/patient-service
        run: |
          IMAGE_NAME=patient-service
          IMAGE_URI=${ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${ECR_REPO_NAME}:$IMAGE_NAME
          docker build -t $IMAGE_NAME .
          docker tag $IMAGE_NAME $IMAGE_URI
          docker push $IMAGE_URI
