name: Deploy to EKS

on:
  push:
    branches: [ main ]
    paths:
      - 'k8s-manifests/**'
      - '.github/workflows/eks-deploy.yaml'

jobs:
  deploy:
    name: Deploy to Amazon EKS
    runs-on: ubuntu-latest

    env:
      AWS_REGION: ${{ secrets.AWS_REGION }}
      EKS_CLUSTER_NAME: ${{ secrets.EKS_CLUSTER_NAME }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Update kubeconfig for EKS
        run: |
          aws eks update-kubeconfig --region $AWS_REGION --name $EKS_CLUSTER_NAME

      - name: Deploy Appointment Service to EKS
        run: |
          kubectl apply -f k8s-manifests/appointment/

      - name: Deploy Patient Service to EKS
        run: |
          kubectl apply -f k8s-manifests/patient/
